task_list:
    path: /
    controller: App\Controller\TaskController::index
    methods: GET

task_create:
    path: /tarea/crear
    controller: App\Controller\TaskController::create
    methods: GET|POST

task_edit:
    path: /tarea/editar/{id_task}
    controller: App\Controller\TaskController::edit
    methods: GET|POST

task_delete:
    path: /tarea/eliminar
    controller: App\Controller\TaskController::delete
    methods: GET
